### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by ItsZer0here** [mlesniew/badtranslator#1]
i run the translator in my windows laptop after adding .py extension and it gave me an error in goslate.py
error:
```python
C:\Users\Nicholas\Downloads\extract-adf\badtranslator>py -3.8 translate.py --language=en "Something"
Traceback (most recent call last):
  File "translate.py", line 64, in <module>
    text = gs.translate(text, language, last)
  File "C:\Program Files\Python38\lib\site-packages\goslate.py", line 407, in translate
    return _unwrapper_single_element(self._translate_single_text(text, target_language, source_language))
  File "C:\Program Files\Python38\lib\site-packages\goslate.py", line 332, in _translate_single_text
    results = list(self._execute(make_task(i) for i in split_text(text)))
  File "C:\Program Files\Python38\lib\site-packages\goslate.py", line 201, in _execute
    yield each()
  File "C:\Program Files\Python38\lib\site-packages\goslate.py", line 330, in <lambda>
    return lambda: self._basic_translate(text, target_language, source_lauguage)[0]
  File "C:\Program Files\Python38\lib\site-packages\goslate.py", line 251, in _basic_translate
    data = {'src': raw_data[-1][0][0]}
IndexError: list index out of range
```
someone pls tell me how to fix im using python 3.8 and 3.10 as parallel versions i ran it with python 3.8 because it is the latest version supporting goslate

**Comment by mlesniew** [comment]
The script was originally written for Python 2.7 and worked with an older goslate version, unfortunately I don't know which exactly.  The code hasn't been touched for over 7 years now, so would need to get refreshed and updated.

If you think you'd be able to cook a patch for this, I will be happy to accept your pull request.

**Comment by RefriZaddo** [comment]
i use python 3.10
